import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTheme } from '../../ThemeContext';
import { Target, MessageSquare, MapPin, GraduationCap, Award, ArrowUpRight, Sparkles, Zap, Terminal, Search, BookOpen, Code2 } from 'lucide-react';
const About = () => {
    const { theme } = useTheme();
    return (_jsxs("section", { id: "about", className: "py-16 lg:py-20 relative overflow-hidden transition-colors duration-500", style: { backgroundColor: theme["base-100"], color: theme["base-content"] }, children: [_jsx("div", { className: "absolute top-0 left-0 w-full h-[1px] opacity-10", style: { backgroundColor: theme.primary } }), _jsxs("div", { className: "max-w-[1400px] mx-auto px-6 lg:px-24 relative z-10", children: [_jsxs("div", { className: "mb-10 lg:mb-14 animate-in fade-in slide-in-from-bottom-4 duration-700", children: [_jsxs("div", { className: "inline-flex items-center gap-2 px-3 py-1 rounded-full border text-[9px] font-black uppercase tracking-[0.2em] mb-4", style: { borderColor: `${theme.primary}33`, color: theme.primary }, children: [_jsx(Terminal, { size: 10, className: "animate-pulse" }), "System.Profile // Laikipia_Node"] }), _jsxs("h2", { className: "text-3xl md:text-5xl font-black uppercase italic tracking-tighter leading-tight", children: ["SOFTWARE ENGINEER ", _jsx("br", {}), _jsx("span", { style: { color: theme.primary }, children: "ARCHITECTING IMPACT." })] })] }), _jsxs("div", { className: "grid lg:grid-cols-12 gap-10 lg:gap-16 items-start", children: [_jsxs("div", { className: "lg:col-span-7 space-y-8 animate-in fade-in slide-in-from-left-8 duration-1000 delay-200", children: [_jsxs("div", { className: "space-y-4 text-sm md:text-base opacity-80 leading-relaxed max-w-2xl", children: [_jsxs("p", { className: "font-bold text-lg flex items-center gap-2", style: { color: theme.primary }, children: [_jsx(Code2, { size: 20 }), " Computer Science @ Laikipia University"] }), _jsxs("p", { children: ["Based in the highlands of ", _jsx("span", { className: "font-bold italic", children: "Nyahururu, Kenya" }), ", I am a ", _jsx("strong", { children: "Software Engineer" }), " and final-year student at ", _jsx("strong", { children: "Laikipia University" }), ". I transform complex logic into scalable products, bridging the gap between academic theory and industry-standard engineering."] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2", children: [
                                                    { icon: _jsx(Target, { size: 14 }), text: "Scalable App Design" },
                                                    { icon: _jsx(MessageSquare, { size: 14 }), text: "Global Collaboration" },
                                                    { icon: _jsx(Zap, { size: 14 }), text: "Full-Stack Architectures" },
                                                    { icon: _jsx(Search, { size: 14 }), text: "Clean & Maintainable Logic" },
                                                ].map((item, i) => (_jsxs("div", { className: "flex items-center gap-3 text-[11px] font-bold uppercase tracking-tight hover:translate-x-2 hover:text-primary transition-all duration-300 cursor-default", children: [_jsx("span", { style: { color: theme.primary }, children: item.icon }), item.text] }, i))) })] }), _jsxs("div", { className: "space-y-4 pt-4", children: [_jsx("h4", { className: "text-[10px] font-black uppercase tracking-[0.3em] opacity-40", children: "Verified Credentials" }), _jsxs("div", { className: "flex flex-wrap gap-4", children: [_jsxs("div", { className: "flex items-center gap-3 p-4 rounded-xl border border-dashed border-opacity-20 transition-all hover:border-solid hover:scale-105 hover:bg-opacity-10 duration-300", style: { borderColor: `${theme.primary}44`, backgroundColor: `${theme.primary}05` }, children: [_jsx(Award, { size: 20, style: { color: theme.primary } }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-black uppercase", children: "Teach2Give" }), _jsx("p", { className: "text-[9px] opacity-60", children: "Software Development Certificate" })] })] }), _jsxs("div", { className: "flex items-center gap-3 p-4 rounded-xl border border-dashed border-opacity-20 transition-all hover:border-solid hover:scale-105 hover:bg-opacity-10 duration-300", style: { borderColor: `${theme.primary}44`, backgroundColor: `${theme.primary}05` }, children: [_jsx(Award, { size: 20, style: { color: theme.primary } }), _jsxs("div", { children: [_jsx("p", { className: "text-[10px] font-black uppercase", children: "SoloLearn" }), _jsx("p", { className: "text-[9px] opacity-60", children: "Basics of Web Dev" })] })] })] })] })] }), _jsx("div", { className: "lg:col-span-5 animate-in fade-in zoom-in-95 duration-1000 delay-500", children: _jsxs("div", { className: "p-8 rounded-[2rem] border relative overflow-hidden group shadow-2xl transition-all duration-500 hover:shadow-primary/10", style: { borderColor: `${theme.primary}22`, backgroundColor: `${theme.primary}03` }, children: [_jsx("div", { className: "space-y-6", children: [
                                                { label: "Role", val: "Software Engineer", icon: _jsx(Code2, { size: 14 }) },
                                                { label: "Institution", val: "Laikipia University", icon: _jsx(BookOpen, { size: 14 }) },
                                                { label: "Course", val: "BSc. Computer Science", icon: _jsx(GraduationCap, { size: 14 }) },
                                                { label: "Current Node", val: "Nyahururu, KE", icon: _jsx(MapPin, { size: 14 }) },
                                            ].map((item, i) => (_jsxs("div", { className: "flex items-center justify-between border-b border-opacity-5 pb-3 group/item transition-colors hover:border-opacity-20", style: { borderColor: theme["base-content"] }, children: [_jsxs("div", { className: "flex items-center gap-2 opacity-50 group-hover/item:opacity-100 transition-opacity", children: [_jsx("span", { style: { color: theme.primary }, children: item.icon }), _jsx("span", { className: "text-[8px] font-black uppercase tracking-widest", children: item.label })] }), _jsx("span", { className: "text-[10px] font-bold italic uppercase", children: item.val })] }, i))) }), _jsxs("div", { className: "mt-8 p-5 rounded-xl border border-opacity-10 relative group-hover:bg-opacity-10 transition-all duration-500", style: { borderColor: theme.primary, backgroundColor: `${theme["base-100"]}ee` }, children: [_jsx(Sparkles, { size: 12, className: "absolute -top-1.5 -right-1.5 animate-bounce", style: { color: theme.primary } }), _jsx("p", { className: "text-[11px] italic font-medium leading-relaxed opacity-70", children: "\"Building high-performance solutions from the heart of Laikipia, focused on global scalability and clean architecture.\"" })] }), _jsxs("button", { className: "mt-8 flex items-center gap-2 text-[9px] font-black uppercase tracking-widest hover:gap-4 transition-all duration-300", style: { color: theme.primary }, children: ["View Full Background ", _jsx(ArrowUpRight, { size: 14 })] })] }) })] })] })] }));
};
export default About;
