import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { useTheme } from '../../ThemeContext';
import { Database, Layout, Settings, Terminal, Globe, Infinity, HardDrive, ChevronDown, ChevronUp } from 'lucide-react';
import { useGetTechSkillsQuery } from '../../Features/Apis/Skills.Api';
const Skills = () => {
    const { theme } = useTheme();
    const { data: techSkills, isLoading } = useGetTechSkillsQuery();
    // FIXED: Added Record type to tell TypeScript this object holds boolean values with string keys
    const [expandedModules, setExpandedModules] = useState({});
    const toggleModule = (id) => {
        setExpandedModules(prev => ({ ...prev, [id]: !prev[id] }));
    };
    const categories = [
        { id: 'frontend', label: 'Frontend Design', icon: _jsx(Layout, { size: 18 }) },
        { id: 'backend', label: 'Backend Development', icon: _jsx(Settings, { size: 18 }) },
        { id: 'database', label: 'Database & Storage', icon: _jsx(Database, { size: 18 }) },
        { id: 'devops', label: 'Deployment & Tools', icon: _jsx(Infinity, { size: 18 }) },
    ];
    if (isLoading)
        return (_jsxs("div", { className: "py-40 flex flex-col items-center justify-center gap-4", children: [_jsx("div", { className: "w-16 h-16 border-t-2 border-r-2 rounded-full animate-spin", style: { borderColor: theme.primary } }), _jsx("p", { className: "text-[10px] font-bold uppercase tracking-widest opacity-40", children: "Loading Skills..." })] }));
    return (_jsx("section", { id: "skills", className: "py-0 relative overflow-hidden transition-colors duration-500", style: { backgroundColor: theme["base-100"], color: theme["base-content"] }, children: _jsxs("div", { className: "max-w-[1400px] mx-auto px-6 lg:px-24 relative z-10", children: [_jsx("div", { className: "flex flex-col lg:flex-row lg:items-end justify-between gap-8 mb-16", children: _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "inline-flex items-center gap-3 px-4 py-1.5 rounded-full border text-[10px] font-bold uppercase tracking-widest", style: { borderColor: `${theme.primary}33`, backgroundColor: `${theme.primary}08`, color: theme.primary }, children: [_jsx(Terminal, { size: 12 }), "Skill List // ", techSkills?.length || 0, " Total items"] }), _jsxs("h2", { className: "text-5xl md:text-7xl font-black uppercase italic tracking-tighter", children: ["MY ", _jsx("span", { style: { color: theme.primary }, children: "SKILLS." })] })] }) }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 items-start", children: categories.map((cat) => {
                        const filteredSkills = techSkills?.filter(tech => tech.category === cat.id) || [];
                        // FIXED: TypeScript now understands this access
                        const isExpanded = !!expandedModules[cat.id];
                        const displaySkills = isExpanded ? filteredSkills : filteredSkills.slice(0, 3);
                        const hasMore = filteredSkills.length > 3;
                        return (_jsxs("div", { className: "group relative p-7 rounded-[2.5rem] border border-opacity-5 transition-all duration-500 hover:shadow-xl", style: {
                                backgroundColor: `${theme["base-content"]}03`,
                                borderColor: `${theme["base-content"]}10`
                            }, children: [_jsxs("div", { className: "flex items-center justify-between mb-8", children: [_jsxs("div", { className: "space-y-1", children: [_jsx("span", { className: "text-[8px] font-bold opacity-30 uppercase tracking-widest", children: cat.id }), _jsx("h3", { className: "text-sm font-bold uppercase italic tracking-wider", children: cat.label })] }), _jsx("div", { className: "p-3 rounded-2xl bg-opacity-10 group-hover:bg-opacity-20 transition-all", style: { backgroundColor: theme.primary, color: theme.primary }, children: cat.icon })] }), _jsxs("div", { className: "space-y-6", children: [displaySkills.map((item) => (_jsxs("div", { className: "group/item relative", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("img", { src: item.icon?.fileUrl, alt: item.name, className: "w-4 h-4 object-contain grayscale group-hover/item:grayscale-0 transition-all" }), _jsx("span", { className: "text-[10px] font-bold uppercase", children: item.name })] }), _jsxs("span", { className: "text-[9px] font-mono opacity-40 group-hover/item:opacity-100", style: { color: theme.primary }, children: [item.skill?.proficiency, "%"] })] }), _jsx("div", { className: "h-[1.5px] w-full bg-opacity-10 rounded-full overflow-hidden", style: { backgroundColor: theme["base-content"] }, children: _jsx("div", { className: "h-full bg-current transition-all duration-1000", style: { width: `${item.skill?.proficiency}%`, color: theme.primary } }) })] }, item.id))), filteredSkills.length === 0 && (_jsxs("div", { className: "py-8 flex flex-col items-center opacity-10", children: [_jsx(HardDrive, { size: 20 }), _jsx("p", { className: "text-[8px] uppercase mt-2 font-bold", children: "No skills added" })] })), hasMore && (_jsx("button", { onClick: () => toggleModule(cat.id), className: "w-full pt-4 flex items-center justify-center gap-2 text-[9px] font-bold uppercase tracking-widest opacity-40 hover:opacity-100 transition-opacity", style: { color: theme.primary }, children: isExpanded ? (_jsxs(_Fragment, { children: [_jsx(ChevronUp, { size: 14 }), " Show Less"] })) : (_jsxs(_Fragment, { children: [_jsx(ChevronDown, { size: 14 }), " Show All (", filteredSkills.length, ")"] })) }))] })] }, cat.id));
                    }) }), _jsxs("div", { className: "mt-16 pt-8 border-t border-dashed border-opacity-10 flex flex-wrap gap-8 justify-between items-center", style: { borderColor: theme["base-content"] }, children: [_jsxs("div", { className: "flex items-center gap-8", children: [_jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[8px] font-bold opacity-30 uppercase", children: "Education" }), _jsx("span", { className: "text-[10px] font-bold", children: "Laikipia University" })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[8px] font-bold opacity-30 uppercase", children: "Location" }), _jsx("span", { className: "text-[10px] font-bold italic", children: "Nyahururu, Kenya" })] }), _jsxs("div", { className: "flex flex-col", children: [_jsx("span", { className: "text-[8px] font-bold opacity-30 uppercase", children: "Role" }), _jsx("span", { className: "text-[10px] font-bold italic", children: "FullSTack Software  Engineer" })] })] }), _jsxs("div", { className: "flex items-center gap-3 font-mono text-[9px] opacity-30", children: [_jsx(Globe, { size: 12 }), _jsx("span", { children: "Status: Ready to work" })] })] })] }) }));
};
export default Skills;
