import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { Mail, Github, Linkedin, ChevronUp, Instagram } from "lucide-react";
import { RiWhatsappFill } from "react-icons/ri";
import { useTheme } from "../ThemeContext";
const menuItems = [
    { name: "Home", path: "/", id: "01" },
    { name: "Projects", path: "/projects", id: "02" },
    { name: "Services", path: "/services", id: "03" },
    { name: "Stack", path: "/tech", id: "04" },
    { name: "Contact", path: "/contact", id: "05" },
];
const Footer = () => {
    const { theme } = useTheme();
    const scrollToTop = () => {
        window.scrollTo({ top: 0, behavior: 'smooth' });
    };
    return (_jsxs("footer", { className: "relative overflow-hidden pt-24 pb-12", style: { backgroundColor: theme["base-100"] }, children: [_jsx("div", { className: "absolute top-0 left-0 w-full h-[1px] bg-gradient-to-r from-transparent via-white/10 to-transparent" }), _jsxs("div", { className: "max-w-7xl mx-auto px-6", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-16 mb-20", children: [_jsxs("div", { className: "lg:col-span-2 space-y-8", children: [_jsxs(Link, { to: "/", className: "inline-block group", children: [_jsxs("span", { className: "text-3xl font-black uppercase italic tracking-tighter", children: ["GAKENYE ", _jsx("span", { style: { color: theme.primary }, children: "NDIRITU" })] }), _jsx("div", { className: "h-1 w-20 mt-2 rounded-full transition-all duration-500 group-hover:w-40", style: { backgroundColor: theme.primary } })] }), _jsx("p", { className: "text-sm leading-relaxed max-w-sm opacity-60", children: "Full-stack developer focused on building scalable, aesthetic, and user-centric digital experiences. Always crafting, always learning." }), _jsxs("div", { className: "flex items-center gap-4 py-4 px-6 rounded-2xl border border-white/5 bg-white/[0.02] w-fit", children: [_jsxs("div", { className: "relative w-2 h-2", children: [_jsx("div", { className: "absolute inset-0 rounded-full animate-ping", style: { backgroundColor: theme.success } }), _jsx("div", { className: "absolute inset-0 rounded-full", style: { backgroundColor: theme.success } })] }), _jsx("span", { className: "text-[10px] font-black uppercase tracking-widest opacity-80", children: "Available for hire" })] })] }), _jsxs("div", { className: "space-y-6", children: [_jsx("h3", { className: "text-[10px] font-black uppercase tracking-[0.3em] opacity-40", children: "Navigation" }), _jsx("div", { className: "flex flex-col gap-4", children: menuItems.map((item) => (_jsxs(Link, { to: item.path, className: "group flex items-center gap-4 text-sm", style: { color: theme["base-content"] }, children: [_jsx("span", { className: "text-[9px] font-mono opacity-30", style: { color: theme.primary }, children: item.id }), _jsx("span", { className: "font-bold opacity-60 group-hover:opacity-100 transition-opacity uppercase tracking-widest text-[11px]", children: item.name })] }, item.name))) })] }), _jsxs("div", { className: "space-y-6", children: [_jsx("h3", { className: "text-[10px] font-black uppercase tracking-[0.3em] opacity-40", children: "Social Networks" }), _jsx("div", { className: "grid grid-cols-2 gap-3", children: [
                                            { icon: _jsx(Github, { size: 18 }), url: "https://github.com/Gakenye8741", label: "GitHub" },
                                            { icon: _jsx(Linkedin, { size: 18 }), url: "https://www.linkedin.com/in/gakenye-ndiritu-9757923a8/", label: "LinkedIn" },
                                            { icon: _jsx(Instagram, { size: 18 }), url: "https://www.instagram.com/_code.d_by_gakenye_/", label: "Instagram" },
                                            { icon: _jsx(RiWhatsappFill, { size: 18 }), url: "https://wa.link/f3ajog", label: "WhatsApp" },
                                        ].map((social, i) => (_jsxs("a", { href: social.url, target: "_blank", rel: "noopener noreferrer", className: "p-4 rounded-2xl border border-white/5 hover:border-primary/30 transition-all hover:-translate-y-1 flex flex-col items-center gap-2", style: { color: theme["base-content"] }, children: [social.icon, _jsx("span", { className: "text-[8px] font-bold uppercase tracking-widest opacity-50", children: social.label })] }, i))) }), _jsxs("a", { href: "mailto:codewithgakenye@gmail.com", className: "flex items-center gap-3 p-4 rounded-xl border border-white/5 hover:border-primary/30 transition-all", children: [_jsx(Mail, { size: 16, style: { color: theme.primary } }), _jsx("span", { className: "text-xs font-bold opacity-70 group-hover:opacity-100", children: "Send an Email" })] })] })] }), _jsxs("div", { className: "pt-10 border-t border-white/5 flex flex-col md:flex-row justify-between items-center gap-8", children: [_jsxs("p", { className: "text-[10px] font-black uppercase tracking-[0.2em] opacity-30", children: ["\u00A9 ", new Date().getFullYear(), " Gakenye Ndiritu. Built with passion."] }), _jsxs("button", { onClick: scrollToTop, className: "flex items-center gap-3 px-6 py-3 rounded-full border border-white/5 hover:border-primary/30 transition-all group", children: [_jsx("span", { className: "text-[10px] font-black uppercase tracking-widest opacity-50 group-hover:opacity-100", children: "Back to Top" }), _jsx(ChevronUp, { size: 16, style: { color: theme.primary } })] })] })] })] }));
};
export default Footer;
